// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import RetreatCards from './RetreatCards';
import Text from './Text';

export {
	CallToAction,
	RetreatCards,
	Text,
};

export const components = {
	call_to_action: CallToAction,
	retreat_cards: RetreatCards,
	text: Text,
};
