import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ContactForm } from "../components/ContactForm";

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact</title>
        <meta name="Coaching site" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactForm />
    </div>
  );
}
